#! /bin/sh
### BEGIN INIT INFO
# Provides: aerospike_librato
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: AeorspikeLibrato
# Description: Aerospike Librato
#
### END INIT INFO

SOURCE_DIR=/opt/aerospike-librato

case "$1" in
 start)
   su joe -c ${SOURCE_DIR}/bin/startup.sh
   ;;
 stop)
   su joe -c ${SOURCE_DIR}/bin/shutdown.sh
   sleep 10
   ;;
 restart)
   su joe -c ${SOURCE_DIR}/bin/shutdown.sh
   sleep 20
   su joe -c ${SOURCE_DIR}/bin/startup.sh
   ;;
 *)
   echo "Usage: aerospike-librato {start|stop|restart}" >&2
   exit 3
   ;;
esac